services:
    app:
        build:
            context: .
            dockerfile: Dockerfile.prod
        environment:
            NODE_ENV: production
            CI: 'true'
        env_file:
            - .env
        ports:
            - '3000:3000'
        restart: always
