volumes:
    app_node_modules:
    pnpm_store:

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - app_node_modules:/app/node_modules
            - pnpm_store:/root/.local/share/pnpm/store
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
        command: sh -c "[ -d node_modules ] || pnpm install; pnpm dev"
        restart: unless-stopped

    storybook:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - app_node_modules:/app/node_modules
            - pnpm_store:/root/.local/share/pnpm/store
        environment:
            NODE_ENV: development
        ports:
            - '6006:6006'
        command: sh -c "[ -d node_modules ] || pnpm install; pnpm storybook -p 6006 --ci"
        restart: unless-stopped

    # docker compose --profile production up -d --build --remove-orphans
    app-prod:
        profiles: ['production']
        build:
            context: .
            dockerfile: Dockerfile.prod
        environment:
            NODE_ENV: production
            CI: 'true'
            PORT: 8080
        env_file:
            - .env
        ports:
            - '8080:8080'
        restart: always
