services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
        command: sh -c "rm -rf node_modules; pnpm install; pnpm dev"
        restart: unless-stopped

    storybook:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
        environment:
            NODE_ENV: development
        ports:
            - '6006:6006'
        command: sh -c "rm -rf node_modules; pnpm install; pnpm storybook -p 6006 --ci"
        restart: unless-stopped

    app-prod:
        profiles: ['production']
        build:
            context: .
            dockerfile: Dockerfile.prod
        environment:
            NODE_ENV: production
            CI: 'true'
            PORT: 8080
        ports:
            - '8080:8080'
        restart: always
