services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        ports:
            - '3000:3000'
        command: sh -c "pnpm install && pnpm dev"
        restart: unless-stopped

    storybook:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - /app/node_modules
        environment:
            NODE_ENV: development
        ports:
            - '6006:6006'
        command: sh -c "pnpm install && pnpm storybook -p 6006 --ci"
        restart: unless-stopped
