name: SSH Deploy (build on server)

on:
    push:
        branches: [main, dev]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Choose branch dir and services
              id: cfg
              run: |
                  BRANCH="${GITHUB_REF##*/}"
                  if [ "$BRANCH" = "main" ]; then
                    echo "DIR=hotel-prod" >> $GITHUB_OUTPUT
                    echo "PROJECT=hotel-prod" >> $GITHUB_OUTPUT
                    echo "SERVICES=app-prod" >> $GITHUB_OUTPUT
                  else
                    echo "DIR=hotel-dev" >> $GITHUB_OUTPUT
                    echo "PROJECT=hotel-dev" >> $GITHUB_OUTPUT
                    echo "SERVICES=app-dev storybook" >> $GITHUB_OUTPUT
                  fi

            - name: SSH to server and deploy
              uses: appleboy/ssh-action@v1.2.0
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.SERVER_SSH_KEY }}
                  script: |
                      set -e
                      cd ~/${{ steps.cfg.outputs.DIR }}
                      git fetch --all
                      git reset --hard origin/${GITHUB_REF##*/}
                      docker compose -p ${{ steps.cfg.outputs.PROJECT }} up -d --build --remove-orphans ${{ steps.cfg.outputs.SERVICES }}
                      docker image prune -f
